/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.demo.Cliente.gui;

import com.example.demo.Cliente.ClienteHttp;
import java.net.http.HttpResponse;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.json.JSONObject;
import com.example.demo.security.JwtUtil;

/**
 *
 * @author bwosi
 */
public class TelaInicial extends javax.swing.JFrame {

    private final ClienteHttp clienteHttp;
    
    public TelaInicial(ClienteHttp clienteHttp) {
        this.clienteHttp = clienteHttp;
        initComponents();
    }
    
    /*public TelaInicial() {
        initComponents();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarEmpresa = new javax.swing.JButton();
        btnCadastrarUsuario = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCadastrarEmpresa.setText("Cadastrar empresa");
        btnCadastrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEmpresaActionPerformed(evt);
            }
        });

        btnCadastrarUsuario.setText("Cadastrar usuário");
        btnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuarioActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrarEmpresa)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnCadastrarUsuario))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnLogin)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnCadastrarEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEmpresaActionPerformed
        new CadastrarEmpresa(clienteHttp).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarEmpresaActionPerformed

    private void btnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioActionPerformed
        new CadastrarUsuario(clienteHttp).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarUsuarioActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        JTextField txtUsuario = new JTextField();
        JTextField txtSenha = new JTextField();
        
        Object[] campos = {
            "Usuário: ", txtUsuario,
            "Senha: ", txtSenha
        };
        
        int option = JOptionPane.showConfirmDialog(this, 
                campos,
                "Login",
                JOptionPane.OK_CANCEL_OPTION
        );
        
        if (option == JOptionPane.OK_OPTION) {
            String usuario = txtUsuario.getText().trim();
            String senha = txtSenha.getText().trim();
            
            if (usuario.isEmpty() || senha.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Preencha usuário e senha!",
                        "Erro de login",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                JSONObject json = new JSONObject();
                json.put("username", usuario);
                json.put("password", senha);
                
                HttpResponse<String> response = clienteHttp.fazerLogin(json.toString());
                
                if (response.statusCode() == 200) {
                    JOptionPane.showMessageDialog(this, "Login realizado com sucesso!");
                    
                    String responseBody = response.body();
                    if (responseBody.contains("\"token\"")) {
                        int start = responseBody.indexOf("\"token\"") + 9;
                        int end = responseBody.indexOf("\"", start);
                        String token = responseBody.substring(start, end);
                        String usernameLogado = usuario;
                        JwtUtil jwtUtil = new JwtUtil();
                        String tipoUsuario = jwtUtil.getRoleFromToken(token);

                        if (tipoUsuario == null) {
                            JOptionPane.showMessageDialog(this, "Não foi possível identificar o tipo de usuário. Será usado USER");
                            tipoUsuario = "USER";
                        }
                        tipoUsuario = tipoUsuario.toUpperCase();
                        
                        this.dispose();
                        
                        if (tipoUsuario.equals("COMPANY") ) {
                            MenuInicialEmpresa menuEmpresa = new MenuInicialEmpresa(clienteHttp, token);
                            menuEmpresa.setVisible(true);
                            
                        }else {
                            MenuInicialUser menuUser = new MenuInicialUser(clienteHttp);
                            menuUser.setVisible(true);
                        }
                    }
                    
                    
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Falha no login: " + response.body());
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao fazer login " + e.getMessage());
                e.printStackTrace(); 
            }

        } else {
            JOptionPane.showMessageDialog(null, "Login cancelado");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarEmpresa;
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JButton btnLogin;
    // End of variables declaration//GEN-END:variables
}
