/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.demo.Cliente.gui.usuario;

import com.example.demo.Cliente.ClienteHttp;
import com.example.demo.Cliente.gui.TelaConexao;
import com.example.demo.Cliente.gui.TelaInicial;
import java.awt.Image;
import java.net.http.HttpResponse;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author bwosi
 */
public class MenuInicialUser extends javax.swing.JFrame {

    private final ClienteHttp clienteHttp;
    private String token;
    
    public MenuInicialUser(ClienteHttp cliente, String token) {
        initComponents();
        
        this.clienteHttp = cliente;
        this.token = token;
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/perfil.png"));
        Image img = icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        btnPerfil.setIcon(new ImageIcon(img));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnBuscarVagas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnPerfil.setText("Meu perfil");

        btnBuscarVagas.setText("Buscar vagas");
        btnBuscarVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVagasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPerfil)
                    .addComponent(btnLogout))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnBuscarVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnPerfil)
                .addGap(19, 19, 19)
                .addComponent(btnBuscarVagas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            HttpResponse<String> response = clienteHttp.logout(token);

            if (response.statusCode() == 200) {
                javax.swing.JOptionPane.showMessageDialog(this, "Logout realizado com sucesso!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Erro no logout: " + response.body());
            }

            token = null;
            
            TelaInicial inicial = new TelaInicial(clienteHttp);
            inicial.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao fazer logout: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBuscarVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVagasActionPerformed
        try {
            String json = "{ \"filters\": [{}] }";

            String companyId = clienteHttp.extrairToken(token);

            HttpResponse<String> response = clienteHttp.buscarVagas(token, json);

            if (response.statusCode() == 200) {
                JSONObject jsonObj = new JSONObject(response.body());
                JSONArray vagas = jsonObj.getJSONArray("items");

                ViewVagasUser viewVagas = new ViewVagasUser(vagas, clienteHttp, token);
                viewVagas.setVisible(true);
                return;

            }
            if (response.statusCode() == 404) {
                JOptionPane.showMessageDialog(this,
                        "Não há vagas cadastradas.");
            } else if (response.statusCode() == 401) {
                JOptionPane.showMessageDialog(this,
                        "Token inválido. Faça login novamente.");
            }

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro inesperado: " + response.body());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao buscar vagas: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarVagasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicialUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicialUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicialUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicialUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenuInicialUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVagas;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPerfil;
    // End of variables declaration//GEN-END:variables
}
